spring:
  application:
    name: config-server

  #we can configure files from either local using native or from git
  cloud:
    config:
      server:
        #        git:
        #          uri: https://github.com/your-org/your-config-repo
        #          clone-on-start: true
        #         OR
        native:
          search-locations:
            - F:\Workspaces\JAVA Stack\Projects\service1.properties
  profiles:
    active:
      - native
server:
  port: 8888

management:
  endpoints:
    web:
      exposure:
        include: "*"  # or include only what you want: "health,info,refresh,env,beans"
  endpoint:
    health:
      show-details: "always"
  info:
    git:
      mode: full
    env:
      enabled: true
  health:
    ldap:
      enabled: false